# Tensorflow 2.0 

TensorFlow started as an open-source deep learning library and has today evolved into an end to end machine learning platform that includes tools, libraries and resources for the research community to push the state of the art in deep learning and developers in the industry to build ML & DL powered applications.

Tensorflow works based on the following two components:



*   Graph
*   Session

A Graph is a connected network of variables created in the tensorflow environment after their initialization. Graph represents the relationship between variables and layers and does not contain the information about the value of the variables. For eg, if you have a=2 and b=3 and c=a+b, a graph views this information like this: there is a variable a, there is a variable b and the variable c is the sum of a and b. But graph does not assign values to a, b or c.

The values associated with the variables are assigned to them using a session. A session is an environment in which objects in the graph are executed. The session holds the values of the elements in the graph. By running a session, we can assign values to the elements in the graph and also perform operation on them. 





## Importing Tensorflow

In [1]:
# Import the 2.0 version of the tensorflow
%tensorflow_version 2.x                            # This line is not required if you are on your own notebook
import tensorflow as tf
print(tf.version)

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x                            # This line is not required if you are on your own notebook`. This will be interpreted as: `2.x`.


TensorFlow 2.x selected.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# What are Tensors?

A Tensor is a generalization of arrays and matrices in higher dimensions. Tensorflow represents tensors as n-dimensional arrays of base data type. 

Tensorflow works by passing and manipulating tensors as its main object. Tensorflow programs work by building a graph of tensor objects that explains how tensors are related. Results are produced by running different parts of the graph. 

Each tensor has a data type and a shape.

Data types include: float32, int32, string and others
Shape: Represents the dimension of the data.

## Creating Tensors

Below is an example of how to create different types of tensors.

In [13]:
string= tf.Variable("This is a string", tf.string)
number= tf.Variable(858, tf.int16)
floating= tf.Variable(5.64, tf.float16)
print(number)                                      # Unlike in tf version 1, wherein we needed to run a session, tf version 2 comes with EAGER EXECUTION- Calculating values as 
                                                   # they occur in our code.

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=858>


In [33]:
# Creating a tensor of constants using tf.constant
a=tf.constant([[1,2,3],[5,6,7]])

# You can get the shape of the tensor using tensor.shape
print("The shape of the tensor using .shape method is", a.shape)          # Only prints the shape of the tensor

print('\n')

# tf.get_shape is equivalent to tf.shape                               
print("The shape of the tensor using .get_shape method is", a.get_shape)  # Prints the tensor along with the shape

The shape of the tensor using .shape method is (2, 3)


The shape of the tensor using .get_shape method is <bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>>


## Rank/Degree of Tensors

Rank of a tensor represents the number of dimensions or independent rows/columns present in the tensor. Tensorflow allows us to create 1 or more dimensional tensors. A one dimensional tensor is called, a scalar.

In [15]:
rank1_tensor= tf.Variable(["Hello"], tf.string)
rank2_tensor= tf.Variable([["Hello", "Kavana"], ["Good", "Morning!"]], tf.string)

# Print the tensor
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Hello', b'Kavana'],
       [b'Good', b'Morning!']], dtype=object)>


Let us determine the rank of the tensor using tf.rank()

In [16]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensors

Shape of a tensor gives the number of rows and columns of the tensor; in other words, it gives the number of elements in each dimension of the tensor. 

We can get the shape of a tensor by using the method tensor.shape

In [17]:
# Let us see how to get the shape of a tensor
rank2_tensor.shape

TensorShape([2, 2])

In [35]:
# We can also use the .get_shape method to get the shape
rank2_tensor.get_shape

<bound method Variable.get_shape of <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Hello', b'Kavana'],
       [b'Good', b'Morning!']], dtype=object)>>

## Changing Shape ( reshape the Tensor)

Often it is necessary that we change the shape of a tensor to make it possible to perform certain operations on the tensor. The number of elements in a tensor is given by the product of size of all its shapes. Hence, it is possible for the same number of elements to have different shapes. 

We can reshape a tensor using:

* tf.reshape(tensor, shape, name=None)


The example below shows how to change the shape of the tensor.

In [42]:
# We can create a tensor of ones with the desired shape using tf.ones(shape, dtype=tf.dtypes.float32, name=None)
tensor1= tf.ones([1,2,3])
tensor2= tf.reshape(tensor1, [2,1,3])      # Reshape tensor1 to shape (2,1,3)
tensor3= tf.reshape(tensor2, [3, -1])     # -1 tells the tensor to calculate the size of the dimension in that place.
                                           # This will reshape the tensor to (3, 2)

Let us see how the 3 tensors look now. Notice the change in their shapes.

In [43]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(2, 1, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensors

There are several types of tensors supported by the tensorflow. The most commonly used tensors are:

* Variable
* Constant
* Placeholder
* SparseTensor

Out of all the above tensors, only Variable is immutable; i.e, it's value may be changed during execution. Rest are all mutable. 

## Some Examples

Let us look at some of the examples of reshaping tensors and some other basic operations.

In [49]:
# Reshape a tensor
t= tf.zeros([5,5,5])
t=tf.reshape(t, [125])               # Reshape the 3-D tensor into a 1-D array; i.e, flatten the tensor
print(t) 

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.], shape=(125,), dtype=float32)


In [50]:
# Another example of reshape
p= tf.ones([3,3,3])
p= tf.reshape(p, [9,3])
print(p)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(9, 3), dtype=float32)
